version: '3.9'
services:
  postgres:
    container_name: rood_postgres
    image: postgres:14.1
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  nginx:
    container_name: rood_nginx
    image: nginx:1.21.6-alpine
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
        - "host.docker.internal:host-gateway"
volumes:
  postgres_volume:
    name: rood_postgres_volume
    driver: local
