version: '3.9'
services:
  postgres:
    container_name: rood_postgres
    image: postgres:14.1
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
    ports:
      - '5432:5432'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  nginx:
    container_name: rood_nginx
    image: nginx:1.21.6-alpine
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
  umami_postgres:
    container_name: umami_postgres
    image: postgres:14.1
    environment:
      - POSTGRES_USER=$UMAMI_DATABASE_USER
      - POSTGRES_PASSWORD=$UMAMI_DATABASE_PASSWORD
      - POSTGRES_DB=$UMAMI_DATABASE_USER
    ports:
      - '5433:5432'
    volumes:
      - umami_volume:/var/lib/postgresql/data
  umami:
    container_name: umami
    build:
      context: ../umami
      args:
        - BASE_PATH=/umami
        - DATABASE_TYPE=postgresql
    depends_on:
      - umami_postgres
    environment:
      # Allows us to change the name of the generated JS file
      # A custom name reduces the chance of ad blockers preventing our analytics from working
      - TRACKER_SCRIPT_NAME=stasi
      - COLLECT_API_ENDPOINT=/stasi/knock
      - DATABASE_URL=postgresql://umami:NC9h7uwqtHGSBr8f@host.docker.internal:5433/umami
      - BASE_PATH=/umami
      - PORT=3100
    ports:
      - '3100:3100'
volumes:
  postgres_volume:
    name: rood_postgres_volume
    driver: local
  umami_volume:
    name: umami_postgres_volume
    driver: local